{{- if .Values.mode.app }}
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "..names.name" . }}-storage
spec:
  accessModes: {{ .Values.persistence.accessModes }}
  storageClassName: {{ .Values.persistence.storageClassName}}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
{{- end }}
