version: "3.9"
services:
  frontend:
    build: .
    command: "frontend"
  backend:
    build: .
    command: "php-fpm"
    environment: 
    - APP_URL=http://localhost12412312
  proxy:
    build: .
    command: "proxy"
  nginx:
    image: nginx
    volumes:
      - .docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
  redis:
    image: "redis:alpine"
