version: "3.9"
services:
  frontend:
    build: .
    command: "frontend"
  backend:
    build: .
    command: "php-fpm"
    environment: 
    - APP_URL=http://localhost
    - REDIS_HOST=redis
    - REDIS_PASSWORD=null
    - REDIS_PORT=6379
    - DB_HOST_MAIN=postgresql
    - DB_DATABASE_MAIN=tribes_community
    - DB_USERNAME_MAIN=tribes
    - DB_PASSWORD_MAIN=tribes1q2w3e4r
  queue-worker:
    build: .
    command: "queue"
    environment: 
    - REDIS_HOST=redis
    - REDIS_PASSWORD=null
    - REDIS_PORT=6379
    - DB_HOST_MAIN=postgresql
    - DB_DATABASE_MAIN=tribes_community
    - DB_USERNAME_MAIN=tribes
    - DB_PASSWORD_MAIN=tribes1q2w3e4r
  schedule:
    build: .
    command: "schedule"
    environment: 
    - REDIS_HOST=redis
    - REDIS_PASSWORD=null
    - REDIS_PORT=6379
    - DB_HOST_MAIN=postgresql
    - DB_DATABASE_MAIN=tribes_community
    - DB_USERNAME_MAIN=tribes
    - DB_PASSWORD_MAIN=tribes1q2w3e4r
  proxy:
    build: .
    command: "proxy"
  nginx:
    image: nginx
    volumes:
      - .docker/docker-compose-ingress-nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
  redis:
    image: "redis:alpine"
  postgresql:
    image: 'bitnami/postgresql:14.5.0-debian-11-r6'
    environment: 
    - POSTGRESQL_USERNAME=tribes_community
    - POSTGRESQL_PASSWORD=tribes1q2w3e4r
    - POSTGRESQL_DATABASE=tribes
