{{- if .Values.mode.migrations }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "..names.name" . }}-migration-{{ .Release.Revision }}
  labels:
    {{- include "..labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  activeDeadlineSeconds: {{ .Values.migrations.activeDeadlineSeconds }}
  backoffLimit: {{ .Values.migrations.backoffLimit }}
  {{- if .Values.migrations.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.migrations.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: {{ include "..names.name" . }}-migration-pull-secret
      containers:
      - name: migrations
        args:
        - artisan
        - migrate
        image: {{ include "..imageName" .Values.backend.image}}
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ include "..names.name" . }}-envs
          - secretRef:
              name: {{ include "..names.name" . }}-envs
{{- end }}
