{{- if .Values.mode.app }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..names.name" . }}-backend
  labels:
    {{- include "..labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "..labels.matchLabels" . | nindent 6 }}
      app: {{ include "..names.name" . }}
  template:
    metadata:
      labels:
        {{- include "..labels.standard" . | nindent 8 }}
        app: {{ include "..names.name" . }}
      annotations:
        checksum/container-registry: {{ include (print $.Template.BasePath "/backend/docker-secret.yaml") . | sha256sum }}
        checksum/envs: {{ include (print $.Template.BasePath "/envs.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
        - name: {{ include "..names.name" . }}-backend-pull-secret
      {{- if .Values.backend.tolerations }}
      tolerations: {{- include "..tplvalues.render" (dict "value" .Values.backend.tolerations "context" .) | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 101
      volumes:
      - name: fpm-socket
        emptyDir: {}
      - name: storage
        persistentVolumeClaim:
          claimName: {{ include "..names.name" . }}-storage
      - name: bank-x509-key
        secret:
          secretName: {{ include "..names.name" . }}-bank-x509-key
      - name: fpm-config
        configMap:
          name: {{ include "..names.name" . }}-fpm
      containers:
        - name: proxy
          image: {{ include "..imageName" .Values.backend.image}}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "..names.fullname" . }}-envs
          - secretRef:
              name: {{ include "..names.fullname" . }}-envs
          args:
          - proxy
          volumeMounts:
          - mountPath: /var/run/php
            name: fpm-socket
          - mountPath: /app/storage
            name: storage
          ports:
          - name: http
            containerPort: {{ .Values.backend.service.port }}
            protocol: TCP
        {{- if .Values.backend.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /healthCheck
              port: http
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.backend.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.backend.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.backend.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /healthCheck
              port: http
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.backend.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.backend.readinessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.backend.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: /healthCheck
              port: http
            failureThreshold: {{ .Values.backend.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.backend.startupProbe.periodSeconds }}
        {{- end }}
        - name: backend
          {{- with .Values.backend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "..imageName" .Values.backend.image}}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          args:
          - php-fpm
          volumeMounts:
          - mountPath: /var/run/php
            name: fpm-socket
          - mountPath: /app/storage
            name: storage
          - mountPath: /app/storage/app/private.key
            name: bank-x509-key
            subPath: private.key
          - mountPath: /usr/local/etc/php-fpm.conf
            name: fpm-config
            subPath: php-fpm.conf
          envFrom:
          - configMapRef:
              name: {{ include "..names.fullname" . }}-envs
          - secretRef:
              name: {{ include "..names.fullname" . }}-envs
        {{- if .Values.backend.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
              - cat
              - /var/run/php/php-fpm.sock
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.backend.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.backend.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.backend.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
              - cat
              - /var/run/php/php-fpm.sock
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.backend.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.backend.readinessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.backend.startupProbe.enabled }}
          startupProbe:
            exec:
              command:
              - cat
              - /var/run/php/php-fpm.sock
            failureThreshold: {{ .Values.backend.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.backend.startupProbe.periodSeconds }}
        {{- end }}
{{- end }}
