{{- if .Values.mode.app }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "..names.name" . }}-fpm
data:
  php-fpm.conf: |
    [global]
    error_log = /proc/self/fd/2
    log_limit = 8192
    daemonize = no 

    [www]
    access.log = /proc/self/fd/2
    clear_env = no
    catch_workers_output = yes
    decorate_workers_output = no
    user = root
    group = root

    listen = /var/run/php/php-fpm.sock
    listen.owner = nginx
    listen.group = nginx

    pm = dynamic
    pm.max_children = {{ .Values.maxChildren }}
    pm.start_servers = {{ .Values.startServers }}
    pm.min_spare_servers = {{ .Values.minSpareServers }}
    pm.max_requests = = {{ .Values.maxRequests }}

{{- end }}
